config/routes.rb
Todos::Application.routes.draw do
  resources :todos do
    member do
      post :toggle
    end

    collection do
      post :toggle_all
      get :active
      get :completed
      delete :destroy_completed
    end

    resources :subtasks, only: [:create, :update, :destroy] do
      member do
        post :toggle
      end
    end
  end

  root to: "todos#index"
end

app/models/sub_todo.rb
class SubTodo < ActiveRecord::Base
  scope :completed, -> { where("completed = ?", true) }
  scope :active, -> { where("completed = ?", false) }

  belongs_to :todo,
    class_name: 'Todo',
    foreign_key: :todo_id

  def title=(title)
    write_attribute(:title, title.strip)
  end

end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  scope :completed, -> { where(completed: true) }
  scope :active, -> { where(completed: false) }

  belongs_to :todo

  def title=(title)
    write_attribute(:title, title.strip)
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  scope :completed, -> { where("completed = ?", true) }
  scope :active, -> { where("completed = ?", false) }

  has_many :subtasks

  def title=(title)
    write_attribute(:title, title.strip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sub_todos_controller.rb
class SubTodosController < ApplicationController
  helper_method :current_filter

  def index
    @sub_todos = SubTodo
  end

  def create
    @todo = Todo.find(params[:todo_id])

    @sub_todo = @todo.sub_todos.new(sub_todo_params)

    @sub_todo.save
  end

  def update
    @sub_todo = SubTodo.find(params[:id])
    @sub_todo.update(sub_todo_params)
  end

  def destroy
    @sub_todo = SubTodo.find(params[:id])
    @sub_todo.destroy
  end

  def toggle
    @sub_todo = SubTodo.find(params[:id])
    @sub_todo.toggle!(:completed)

    @todo = @sub_todo.todo
    @complete = Todo.check_all_subs(@todo)
  end

  private

  def sub_todo_params
    params.require(:sub_todo).permit(:title, :completed, :todo_id)
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  def create
    @subtask = todo.subtasks.new(subtask_params)
    @subtask.save
  end

  def toggle
    subtask.toggle!(:completed)
  end

  def update
    subtask.update(subtask_params)
  end

  def destroy
    subtask.destroy
  end

  private

  def subtask_params
    params.require(:subtask).permit(:title, :completed)
  end

  def subtask
    @subtask ||= todo.subtasks.find(params[:id])
  end

  def todo
    @todo ||= Todo.find(params[:todo_id])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  helper_method :current_filter

  def index
    @todos = Todo
  end

  def active
    @todos = Todo.active

    set_current_filter(:active)

    render :index
  end

  def completed
    @todos = Todo.completed

    set_current_filter(:completed)

    render :index
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
  end

  def destroy_completed
    @todos_for_destruction = Todo.completed.all

    Todo.completed.destroy_all
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
  end

  def toggle
    @todo = Todo.find(params[:id])
    @todo.toggle!(:completed)

    @todo.sub_todos.update_all(completed: @todo.completed)
  end

  def toggle_all
    Todo.update_all(completed: params[:completed] ? 't' : 'f')

    @todos = Todo.all
  end

private

  def todo_params
    params.require(:todo).permit(:title, :completed)
  end

  def set_current_filter(filter)
    @current_filter = filter
  end

  def current_filter
    @current_filter
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sub_todos_helper.rb
module SubTodosHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def todos_filter_class
    "filtered " + current_filter.to_s
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/todos.js.erb
<%= yield %>

$("#toggle-all").prop("checked", <%= Todo.active.count == 0 %>);

$("#todoapp").toggleClass("has_todos", <%= Todo.count > 0 %>);

$("#footer").replaceWith("<%= j(render("footer")) %>");

app/views/sub_todos/_destroy.js.erb
$("#<%= dom_id(sub_todo) %>").remove();

app/views/sub_todos/_sub_todo.html.erb
<li class="sub_todo<%= " completed" if sub_todo.completed? %>" id="<%= dom_id(sub_todo) %>">
  <div class="sub-todo-view">
    <%= form_for(sub_todo, url: toggle_todo_sub_todo_path(sub_todo.todo, sub_todo), method: :post, remote: true) do |f| %>
      <%= f.check_box :completed, class: "sub-todo-toggle", "data-behavior" => "submit_on_check" %>
    <% end %>
    <label class="sub-todo-label" data-behavior="sub_todo_title"><%= sub_todo.title %></label>
    <%= form_for(sub_todo, url: todo_sub_todo_path(sub_todo.todo, sub_todo), method: :delete, remote: true) do |f| %>
      <button type="submit" class="destroy"></button>
    <% end %>
  </div>
  <%= form_for(sub_todo, url: todo_sub_todo_path(sub_todo.todo, sub_todo), remote: true, html: { "data-behavior" => "edit_todo_form" }) do |f| %>
    <%= f.text_field :title, class: "edit", "data-behavior" => "sub_todo_title_input", "data-original-value" => sub_todo.title %>
  <% end %>
</li>

app/views/sub_todos/_toggle.js.erb
$("#<%= dom_id(sub_todo) %>")
  .toggleClass("completed", <%= sub_todo.completed? %>)
  .find("input.sub-todo-toggle")
  .prop("checked", <%= sub_todo.completed? %>);

<% if complete %>
  $("#<%= dom_id(todo) %>")
    .toggleClass("completed", <%= todo.completed? %>)
    .find("input.todo-toggle")
    .prop("checked", <%= todo.completed? %>);
<% end %>

app/views/sub_todos/create.js.erb
$("#sub-todo-list-<%= @sub_todo.todo_id %>").append("<%= j(render(@sub_todo)) %>");

$(".new-sub-todo").val("");

app/views/sub_todos/destroy.js.erb
<%= render "destroy", sub_todo: @sub_todo %>

app/views/sub_todos/toggle.js.erb
<%= render "toggle", sub_todo: @sub_todo, todo: @todo, complete: @complete %>

app/views/sub_todos/update.js.erb
$("#<%= dom_id(@sub_todo) %>").replaceWith("<%= j(render(@sub_todo)) %>");

app/views/subtasks/_subtask.html.erb
<li class="<%= "completed" if subtask.completed? %>" id="<%= dom_id(subtask) %>">
  <div class="view">
    <%= form_for(subtask, url: toggle_todo_subtask_path(subtask.todo, subtask), method: :post, remote: true) do |f| %>
      <%= f.check_box :completed, class: "toggle", "data-behavior" => "submit_on_check" %>
    <% end %>
    <label data-behavior="todo_title"><%= subtask.title %></label>
    <%= form_for([subtask.todo, subtask], method: :delete, remote: true) do |f| %>
      <button type="submit" class="destroy"></button>
    <% end %>
  </div>
  <%= form_for([subtask.todo, subtask], remote: true, html: { "data-behavior" => "edit_todo_form" }) do |f| %>
    <%= f.text_field :title, class: "edit", "data-behavior" => "todo_title_input", "data-original-value" => subtask.title %>
  <% end %>
</li>

app/views/subtasks/create.js.erb
$("#subtask-list-<%= dom_id(@subtask.todo) %>").append("<%= j(render(@subtask)) %>");

$("#new-subtask-<%= dom_id(@subtask.todo) %>").val("");

app/views/subtasks/destroy.js.erb
$("#<%= dom_id(@subtask) %>").remove();

app/views/subtasks/toggle.js.erb
$("#<%= dom_id(@subtask) %>")
  .toggleClass("completed", <%= @subtask.completed? %>)
  .find("input.toggle")
  .prop("checked", <%= @subtask.completed? %>);

<% if @subtask.todo.subtasks.all?(&:completed?) %>
  $("#<%= dom_id(@subtask.todo) %>").find("input.toggle").trigger('click');
<% end %>

app/views/subtasks/update.js.erb
$("#<%= dom_id(@subtask) %>").replaceWith("<%= j(render(@subtask)) %>");

app/views/todos/_destroy.js.erb
$("#<%= dom_id(todo) %>").remove();

app/views/todos/_footer.html.erb
<footer id="footer">
  <span id="todo-count"><strong><%= Todo.active.count %></strong> <%= "item".pluralize(Todo.active.count) %> left</span>

  <ul id="filters">
    <li>
      <%= link_to "All", todos_path, class: "all" %>
    </li>
    <li>
      <%= link_to "Active", active_todos_path, class: "active" %>
    </li>
    <li>
      <%= link_to "Completed", completed_todos_path, class: "completed" %>
    </li>
  </ul>

  <% if Todo.completed.count > 0 %>
  <%= form_tag(destroy_completed_todos_path, method: :delete, remote: true) do %>
    <button id="clear-completed" type="submit">Clear completed (<%= Todo.completed.count %>)</button>
  <% end %>
  <% end %>
</footer>

app/views/todos/_todo.html.erb
<li class="<%= "completed" if todo.completed? %>" id="<%= dom_id(todo) %>">
  <div class="view">
    <%= form_for(todo, url: toggle_todo_path(todo), method: :post, remote: true) do |f| %>
      <%= f.check_box :completed, class: "toggle", "data-behavior" => "submit_on_check" %>
    <% end %>
    <label data-behavior="todo_title"><%= todo.title %></label>
    <%= form_for(todo, method: :delete, remote: true) do |f| %>
      <button type="submit" class="destroy"></button>
    <% end %>
  </div>
  <%= form_for(todo, remote: true, html: { "data-behavior" => "edit_todo_form" }) do |f| %>
    <%= f.text_field :title, class: "edit", "data-behavior" => "todo_title_input", "data-original-value" => todo.title %>
  <% end %>

  <div class="subtasks">
    <%= form_for([todo, todo.subtasks.new], remote: true) do |f| %>
      <%= f.text_field :title, placeholder: "What needs to be done?", id: "new-subtask-#{dom_id(todo)}", autofocus: true, "data-behavior" => "submit_on_enter" %>
    <% end %>

    <ul id="subtask-list-<%= dom_id(todo) %>" class="subtask-list">
      <%= render todo.subtasks.delete_if(&:new_record?) %>
    </ul>
  </div>
</li>

app/views/todos/_toggle.js.erb
$("#<%= dom_id(todo) %>")
  .toggleClass("completed", <%= todo.completed? %>)
  .find("input.todo-toggle")
  .prop("checked", <%= todo.completed? %>);

<% todo.sub_todos.each do |sub_todo| %>
  $("#<%= dom_id(sub_todo) %>")
    .toggleClass("completed", <%= sub_todo.completed? %>)
    .find("input.sub-todo-toggle")
    .prop("checked", <%= sub_todo.completed? %>);
<% end %>

app/views/todos/create.js.erb
$("#todo-list").append("<%= j(render(@todo)) %>");

$("#new-todo").val("");

app/views/todos/destroy.js.erb
<%= render "destroy", todo: @todo %>

app/views/todos/destroy_completed.js.erb
<%= render partial: "destroy", collection: @todos_for_destruction, as: :todo %>

app/views/todos/index.html.erb
<section id="todoapp" class="<%= "has_todos" if @todos.unscoped.count > 0 %> <%= todos_filter_class %>">


  <header id="header">
    <h1>todos</h1>
    <%= form_for(Todo.new, remote: true) do |f| %>
      <%= f.text_field :title, placeholder: "What needs to be done?", id: "new-todo", autofocus: true, "data-behavior" => "submit_on_enter" %>
    <% end %>
  </header>


  <section id="main">
    <%= form_tag(toggle_all_todos_path, method: :post, remote: true) do %>
      <input name="completed" id="toggle-all" type="checkbox" value="true" data-behavior="submit_on_check" <%= "checked" if @todos.active.count == 0 %>>
    <% end %>
    <label for="toggle-all">Mark all as complete</label>
    <ul id="todo-list">
      <%= render @todos.all %>
    </ul>
  </section>


  <%= render "footer" %>


</section>


<footer id="info">
  <p>Click a todo to add and view sub tasks</p>
  <p>Double-click to edit a todo</p>
  <p>Created by <a href="mailto: smidwap@gmail.com">Matt De Leon</a></p>
  <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>

app/views/todos/toggle.js.erb
<%= render "toggle", todo: @todo %>

app/views/todos/toggle_all.js.erb
<%= render partial: "toggle", collection: @todos, as: :todo %>

app/views/todos/update.js.erb
$("#<%= dom_id(@todo) %>").replaceWith("<%= j(render(@todo)) %>");